version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "daily"

    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      middy:
        patterns:
          - "@middy/*"

      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/app"

    schedule:
      interval: "daily"

    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      middy:
        patterns:
          - "@middy/*"

      dev-dependencies:
        applies-to: "version-updates"
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
