FROM public.ecr.aws/aws-cli/aws-cli:2.15.2 AS aws-cli

FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:1-20

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends default-jdk \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=aws-cli /usr/local/aws-cli /usr/local/aws-cli
RUN ln -s /usr/local/aws-cli/v2/current/bin/aws /usr/local/bin/aws

USER node
