name: Test and lint

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Reconfigure git to not use auth in URLs
        run: >
          git config --global url."https://github.com/".insteadOf
          git@github.com:

      - name: Enable corepack
        run: |
          corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        env:
          COREPACK_ENABLE_STRICT: false
        with:
          cache-dependency-path: pnpm-lock.yaml
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build generated libraries
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: pnpm gen
          retry_on: error

      - name: Run tests
        run: pnpm test

      - name: Run linter
        run: pnpm lint .

      - name: Run prettier
        run: pnpm prettier --check .
